"""The published family in one place.

`docs/models.md`, the table in every model card and the README all read from here, so adding
a model is one line and the numbers cannot drift apart. Every cell comes from the evaluation
files the run directory holds; a run that is not on this machine shows "-".
"""

from __future__ import annotations

import dataclasses
import json
import os


@dataclasses.dataclass(frozen=True)
class Model:
    name: str
    run: str
    backbone: str
    size: str


FAMILY = [
    Model("assay-0.6b", "runs/assay-0.6b-v4", "Qwen3-0.6B-Base", "0.6B"),
    Model("assay-1.7b", "runs/assay-1.7b-v2", "Qwen3-1.7B-Base", "1.7B"),
    Model("assay-4b", "runs/assay-4b-v4", "Qwen3-4B-Base", "4B"),
    Model("assay-27b", "runs/assay-27b", "Qwen3.8-27B (4-bit)", "27B"),
    Model("assay-compiled-base", "runs/compiled-late-gte-base", "gte-modernbert-base", "149M"),
]
HUB = "https://huggingface.co/Berk"


def overall(run: str, split: str) -> dict | None:
    path = os.path.join(run, f"eval-{split}-scaled.json")
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)["overall"]


def cells(run: str, split: str, ece: bool = True) -> str:
    o = overall(run, split)
    if o is None:
        return "-"
    if ece:
        return f"{o['accuracy']:.3f} / {o['brier']:.3f} / {o['ece']:.3f}"
    return f"{o['accuracy']:.3f} / {o['brier']:.3f}"


def abstention(run: str) -> str:
    path = os.path.join(run, "conformal-eval.json")
    if not os.path.exists(path):
        return "-"
    with open(path) as f:
        ev = json.load(f).get("holdout", {})
    parts = []
    for qtype in ("bool", "choice"):
        v = ev.get(qtype)
        if v and v["act_rate"] > 0:
            parts.append(f"{qtype} {v['act_rate']:.0%} at {v['act_error']:.1%}")
    return ", ".join(parts) or "-"


def latency(run: str) -> str:
    for name in ("latency.txt", "latency-cpu.txt"):
        path = os.path.join(run, name)
        if not os.path.exists(path):
            continue
        with open(path) as f:
            rows = [line.split() for line in f if line.strip() and line.split()[0].isdigit()]
        if not rows:
            continue
        one = next((r[1] for r in rows if r[0] == "1"), "-")
        many = next((r[1] for r in rows if r[0] == "24"), "-")
        where = "CPU" if name.endswith("cpu.txt") else "GPU"
        return f"{one} / {many} ms ({where})"
    return "-"


def short_table() -> str:
    """The table that goes in every model card: size and the two splits that matter."""
    lines = [
        "| model | size | unseen tasks | transfer-v4 |",
        "|---|---|---|---|",
    ]
    for m in FAMILY:
        lines.append(
            f"| [{m.name}]({HUB}/{m.name}) | {m.size} | "
            f"{cells(m.run, 'holdout', ece=False)} | {cells(m.run, 'transfer-v4', ece=False)} |"
        )
    return "\n".join(lines)


def full_table() -> str:
    lines = [
        (
            "| model | backbone | size | seen (dev) | unseen (holdout) | transfer-v4 "
            "| abstention (unseen) | latency |"
        ),
        "|---|---|---|---|---|---|---|---|",
    ]
    for m in FAMILY:
        lines.append(
            f"| [{m.name}]({HUB}/{m.name}) | {m.backbone} | {m.size} | "
            f"{cells(m.run, 'dev')} | {cells(m.run, 'holdout')} | {cells(m.run, 'transfer-v4')} | "
            f"{abstention(m.run)} | {latency(m.run)} |"
        )
    return "\n".join(lines)


def document() -> str:
    """docs/models.md, regenerated by scripts/family_table.py."""
    return f"""# The Assay model family

Every row is the same recipe on a different backbone, evaluated on the same splits. Cells are
accuracy / Brier / ECE after one temperature fitted on seen-task calibration data. Unseen
tasks are eleven datasets never trained on; the transfer suite is `jaredpalmer/kev-suites`
transfer-v4 dev, whose sources are excluded from training. Abstention is the fitted conformal
act rate and the error among answers acted on, at alpha 0.1, measured on unseen tasks.
Latency is one question / 24 packed questions over one state.

{full_table()}

All weights are Apache-2.0. Training data: 55 public datasets rendered as typed questions
plus our own generators, published at
[Berk/assay-synthetic](https://huggingface.co/datasets/Berk/assay-synthetic).
"""
