"""Publish the synthetic datasets to the Hugging Face Hub.

    uv run python -m assay.publish_data --repo Berk/assay-synthetic

Only material generated by this repository is published: the policy-application and date
reasoning generators and the rubric question bank. The public datasets Assay trains on are
not redistributed: they keep their own licences (several non-commercial), and
docs/datasets.md lists them with their sources.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil

from huggingface_hub import HfApi

from assay.data.dates import generate as generate_dates
from assay.data.policy import generate as generate_policy
from assay.data.policy import generate_hard
from assay.data.registry import Example
from assay.data.rubrics import question_bank
from assay.records import question_to_dict, write_record

CONFIGS = {
    "policy": (
        generate_policy,
        "Rule application: a policy built from AND/OR/NOT/IF-ELSE over stated facts, and a case; the verdict is computed in code.",
    ),
    "policy_hard": (
        generate_hard,
        "The same, harder: nesting depth 3, predicates over text as well as numbers, and cases where a fact the rule needs is missing (answerable=false).",
    ),
    "dates": (
        generate_dates,
        "Deadline reasoning: a rule with a grace period, two dates in varied formats (ISO, long, short, weekday, relative), and the verdict.",
    ),
}


def write_split(path: str, examples: list[Example], source: str) -> None:
    with open(path, "w") as f:
        for i, ex in enumerate(examples):
            write_record(
                f,
                ex.state,
                {ex.name: (ex.question, ex.label, ex.target, ex.answerable)},
                {"source": source, "id": f"{source}/{i}"},
            )


def card(repo: str, counts: dict[str, dict[str, int]]) -> str:
    configs = "\n".join(
        f"""  - config_name: {name}
    data_files:
      - split: train
        path: {name}/train.jsonl
      - split: test
        path: {name}/test.jsonl"""
        for name in CONFIGS
    )
    table = "\n".join(
        f"| `{name}` | {counts[name]['train']} | {counts[name]['test']} | {CONFIGS[name][1]} |"
        for name in CONFIGS
    )
    return f"""---
license: apache-2.0
language:
- en
task_categories:
- text-classification
- question-answering
tags:
- synthetic
- reasoning
- calibration
- assay
configs:
{configs}
---

# {repo.split("/")[-1]}

Synthetic decision tasks generated by the [Assay](https://github.com/bgokden/assay) project.
Each item is a **state** (the facts), a **typed question** (`bool`, `choice` or `score` with
described options) and a label computed in code, so the labels are exact rather than
annotated. They were written to fix two measured weaknesses of decision models: composing
rules and reasoning about dates. On our public transfer suite, adding them to training moved
deadline accuracy from 0.60 to 0.975 and rule-composition families by 3 to 12 points.

| config | train | test | what it is |
|---|---|---|---|
{table}

## Format

One JSON object per line:

```json
{{"state": {{"policy": "...", "case": "..."}},
 "questions": {{"verdict": {{"type": "score", "instructions": "How late is the report?",
                            "levels": ["On time", "Late but accepted", "Refused"], "label": 1}}}},
 "meta": {{"source": "dates", "id": "dates/0"}}}}
```

`state` is a string or an object of named fields. Each question carries its type and its
options: `options` (a map from option key to description) for `choice`, `levels` (ordered,
low to high) for `score`, optional `yes`/`no` descriptions for `bool`. `label` is the option
key, a boolean or a level index. `answerable` is `false` when the state is missing a fact the
rule needs, which is the case in part of `policy_hard`: a model should say so rather than
guess. Some items carry `target`, a probability distribution over the options, when the label
is soft.

The `rubrics.json` file holds the 90 generic questions (50 `bool`, 20 `choice`, 20 `score`)
that Assay uses to label unlabelled text with a teacher model; they are reusable as a
distillation or evaluation rubric bank.

## Uses

Training or evaluating models that must apply rules exactly, follow nested conditions, refuse
when information is missing, or compare dates written in different formats. The verdicts are
computed, so the test splits are reliable as an evaluation of that capability, and a model
that has not seen the generators cannot have memorised them.

## Generation

Everything here is produced by code in the Assay repository
(`assay/data/policy.py`, `assay/data/dates.py`, `assay/data/rubrics.py`); no text is taken
from any other dataset. Regenerate at any size with a different seed:

```python
from assay.data.policy import generate, generate_hard
from assay.data.dates import generate as generate_dates

examples = generate(10_000, seed=0) + generate_hard(10_000, seed=1) + generate_dates(10_000, seed=2)
```

## The models trained on it

The [Assay collection](https://huggingface.co/collections/Berk/assay-calibrated-typed-decisions-6ab2fcb2b7eea0b7aaf785ab)
holds the models this data was generated for: four decoder sizes from 0.6B to 27B and an
encoder tier, each answering typed questions with calibrated probabilities, an evidence score
and conformal abstention. `python -m assay.pipeline` trains one on data in this format.

## Licence and scope

Apache-2.0. This repository contains **only** generated material. Assay also trains on public
datasets which are *not* redistributed here; they keep their own licences, several of them
non-commercial, and are listed with their sources in
[docs/datasets.md](https://github.com/bgokden/assay/blob/main/docs/datasets.md).
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--train", type=int, default=50000, help="items per config in the train split")
    ap.add_argument("--test", type=int, default=2000, help="items per config in the test split")
    ap.add_argument("--out", default="data/release", help="staging directory")
    ap.add_argument("--seed", type=int, default=101)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--card-only", action="store_true", help="upload just the dataset card")
    args = ap.parse_args()
    if args.card_only:
        # the counts are what was published; regenerating 100k items to fix a sentence is waste
        counts = {name: {"train": args.train, "test": args.test} for name in CONFIGS}
        os.makedirs(args.out, exist_ok=True)
        path = os.path.join(args.out, "README.md")
        with open(path, "w") as f:
            f.write(card(args.repo, counts))
        if args.dry_run:
            print(f"wrote {path}")
            return
        HfApi().upload_file(
            path_or_fileobj=path,
            path_in_repo="README.md",
            repo_id=args.repo,
            repo_type="dataset",
        )
        print(f"updated https://huggingface.co/datasets/{args.repo}")
        return
    if os.path.exists(args.out):
        shutil.rmtree(args.out)
    os.makedirs(args.out)
    counts: dict[str, dict[str, int]] = {}
    for i, (name, (generate, _)) in enumerate(CONFIGS.items()):
        os.makedirs(os.path.join(args.out, name))
        # different seeds for train and test, so the splits do not overlap
        train = generate(args.train, args.seed + i)
        test = generate(args.test, args.seed + 500 + i)
        write_split(os.path.join(args.out, name, "train.jsonl"), train, name)
        write_split(os.path.join(args.out, name, "test.jsonl"), test, name)
        counts[name] = {"train": len(train), "test": len(test)}
        print(f"{name}: {len(train)} train, {len(test)} test", flush=True)
    with open(os.path.join(args.out, "rubrics.json"), "w") as f:
        json.dump([question_to_dict(q) for q in question_bank()], f, indent=1)
    with open(os.path.join(args.out, "README.md"), "w") as f:
        f.write(card(args.repo, counts))
    print(f"staged {args.out}: {sorted(os.listdir(args.out))}")
    if args.dry_run:
        return
    api = HfApi()
    api.create_repo(args.repo, repo_type="dataset", exist_ok=True)
    api.upload_folder(folder_path=args.out, repo_id=args.repo, repo_type="dataset")
    print(f"uploaded to https://huggingface.co/datasets/{args.repo}")


if __name__ == "__main__":
    main()
